artist:
  name: Handy Men Chicago
  tagline: We fix and design all your home needs!
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone:
  # contact_email:

social:
  - name: Facebook
    url: https://www.facebook.com/Chicago-Handyman-Services-1461168677348603/
  - name: Instagram
    url: https://www.instagram.com/chitownhandymen/
  - name: Twitter
    url: https://twitter.com
  - name: Youtube
    url: https://youtube.com

site_language: en
